### ISSUE TITLE
Unable to set a custom header ID

### ISSUE THREAD

**Issue by scfarley** [kpym/gm#1]
Prior to commit a8616f1e6d183ef58c367d34a780739b1c1a79a8, setting a custom header ID was possible.

Example:
```markdown
# Testing {#atag}
```

Prior output:
```html
...
<h1 id="atag">Testing</h1>
...
```

Current output:
```html
...
<h1 id="testing-atag">Testing {#atag}</h1>
...
```

**Comment by scfarley** [comment]
Unrelated to this issue, but at https://github.com/kpym/gm/blob/main/gm_parameters.go#L29.  `version` is missing an `n` at the end of the header.

**Comment by kpym** [comment]
I switched to [github.com/mdigger/goldmark-attributes](https://github.com/mdigger/goldmark-attributes) in the hope that attribute tags will be handled better. I'll revert to the previous situation and try to find a good solution later.

Thanks for the typo : I'll fix it.
